#!/usr/bin/env bash
: '
Usage : gitdop "commit message"

This script automates the git commands I use often.
It displays the results of `git status` and asks whether to proceed.
On confirmation, it will continue to add, commit, and push to the current branch (HEAD).

Inspired by the bashrc at https://github.com/daniruiz/dotfiles/blob/master/.bashrc
'
RED='\033[1;31m'
GREEN='\033[1;32m'
RCOL='\033[0m'

git status
echo -e "${GREEN}[*] Continue ?${RCOL}"
read response
if [ $response == "y" ] || [ $response == "Y" ]
then
	git add .
	echo -e "${GREEN}[+] Added.${RCOL}"
	git commit -m "$@"
	echo -e "${GREEN}[+] Commited.${RCOL}"
	git push origin HEAD
	echo -e "${GREEN}[+] Pushed.${RCOL}"
else
	echo -e "${RED}[x] Aborted.${RCOL}"
fi

