#!/usr/bin/env bash

RED='\033[1;31m'
GREEN='\033[1;32m'
RCOL='\033[0m'

git status
echo -e "${GREEN}[*] CONTINUE ?${RCOL}"
read response
if [ $response == "y" ] || [ $response == "Y" ]
then
	git add .
	echo -e "${GREEN}[+] Added.${RCOL}"
	git commit -m "$@"
	echo -e "${GREEN}[+] Commited.${RCOL}"
	git push origin HEAD
	echo -e "${GREEN}[+] Pushed.{$RCOL}"
else
	echo -e "${RED}[x] Aborted.${RCOL}"
fi

