#!/usr/bin/env bash
: '
A simple script combining systemctl commands I use often.
'

services=(httpd mysqld mssql-server docker)

if [ -z "$1" ]
then
	for svc in "${services[@]}"
	do
		cmd="systemctl --no-pager status $svc"
		result=$($cmd)
		readarray -t lines <<<"$result"
		echo "${lines[0]}"
		echo "${lines[2]}"
	done
elif [ "$1"="stopall" ]
then
	for svc in "${services[@]}"
	do
		eval "systemctl stop $svc"
	done
fi

